# Generated by Django 4.1.2 on 2022-11-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=20)),
                ('bookName', models.CharField(max_length=100)),
                ('bookAvailability', models.BooleanField()),
            ],
            options={
                'db_table': 'library',
            },
        ),
    ]
